### ISSUE TITLE
Foundation is not a function error on 6.4.1

### ISSUE THREAD

**Issue by Laraveldeep** [zurb/foundation-sites#10443]
Hi,

I have npm install of foundation 6.4.1 with jquery 2.2.4 on my new laravel app that uses laravel-mix.

in my `app.js`, I have
```
require('foundation-sites');
$(document).foundation();
```

But I am seeing `Foundation is not a function` error on console. So the dropdown menu I am trying to use doesn't function.

To fix this I have changed it to
```
require('foundation-sites/dist/js/foundation');
$(document).foundation();
```

This stops the error but dropdown menu doesn't work at all. I have tried to test with orbit slider code. No success. I guess component that requires javascript doesn't work at all... However I have SCSS part working nicely.

Any suggestion?
Thanks!

**Comment by Laraveldeep** [comment]
By the way above method used to work on 6.2 version. 

Solved the issue by moving foundation initialization script on the page.

```
<script src="webpack minified scripts"></script>
<script>$(document).foundation();</script>
```
