### ISSUE TITLE
Slider component doesn't work with current jQuery version 3.1.1 

### ISSUE THREAD

**Issue by Kobe** [zurb/foundation-sites#10876]
TypeError: this.handles.addTouch is not a function

**Comment by ncoden** [comment]
Hi @Kobe. Could you provide the whole error stacktrace please ?

**Comment by Kobe** [comment]
Sorry, my fault. I ran into side effect. There is no issue with the current jQuery version!
