### ISSUE TITLE
Foundation 5.3.3 - Reveal modal doesn't work with jquery 2.2.0

### ISSUE THREAD

**Issue by roundge** [zurb/foundation-sites#7884]
Hi there,

As mentioned here : http://foundation.zurb.com/forum/posts/37579-reveal-stopped-working
Reveal modal doesn't work anymore with the jquery update (2.2.0)

Firebug in firefox shows this message : 
`TypeError: g.on(...).trigger is not a function`

it works if you downgrade to jquery 2.1.4

**Comment by wneessen** [comment]
Confirmed. Same issue for me as well.

**Comment by gakimball** [comment]
Merged #7859 which resolves this.

**Comment by timaschew** [comment]
Why this issue is closed? The issue is not fixed!
There is no foundation 5.3.4 or something else, installing version 5.* via bower is still broken!

**Comment by wneessen** [comment]
Agreed. Though, you can fix it by manually applying the patch as described in https://github.com/sjhewitt/foundation/commit/2e33179ad78b7d677610c50656f51f4b703034d5

**Comment by gakimball** [comment]
@timaschew The fix is in the codebase, so we close the issue. We'll try to get a patch out for Foundation 5 soon.

**Comment by mpasternak** [comment]
This is NOT fixed in 5.5.3, 

please release 5.5.4 legacy version that fixes that,

5.5.3 still needs downgrade of jQuery to 2.1.4
